--- #YAML:1.0
name:               AnyEvent-XMPP
version:            0.51
abstract:           An implementation of the XMPP Protocol
author:
    - Robin Redeker <elmex@ta-sa.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyEvent:            0
    AnyEvent::Handle:    0
    AnyEvent::Socket:    0
    Authen::SASL:        0
    Digest::SHA1:        0
    MIME::Base64:        0
    Net::LibIDN:         0
    Object::Event:       0.7
    Scalar::Util:        0
    XML::Parser::Expat:  0
    XML::Writer:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
